### PR TITLE
CV but easier

### PR DESCRIPTION
**Pull request by jbencook**
This is a first pass at a CV environment for Python. This image will run a Jupyter notebook server so you can dev locally through your browser, but it can also serve as the base for a production container.

screenshot

The README describes a few things about running it and I'm currently storing the image at `hudl/cvpy:latest`.

If you also expose port 22, you can configure PyCharm to sync source code with the container when you save changes.

### CODE REVIEW

**Comment by jbencook** [comment]
Let me know what you think about these changes @rversaw. Everything is now working the same as described above for a jupyter notebook, but I want to make sure I didn't mess anything up for VS.

Also, I tried `git checkout --branch 3.0.0 --depth 1` but our version of `git` didn't like either option. I also tried `git checkout tag/3.0.0`, which also made `git` choke :( I went back to what I know works for now, but another option is to `wget` the releases we want to use.

**Comment by jbencook** [comment]
Maybe CC @rlhotovy since you're maintainer on the `cvdev` container.

**Comment by rversaw** [comment]
@jbencook I think the tagged checkout should actually be `git checkout tags/3.0.0` if you want that. It shouldn't really matter much, though. In the end, checking it out with `3.0.0` as the branch should be fine.

**Comment by jbencook** [comment]
:facepalm: I'll give that a try :)

**Comment by jbencook** [comment]
That worked @rversaw

**Pull request merged**
